# deployment.yaml defines the deployment of the application pods
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
  namespace: node-space
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: node-app-container
        # The image to use for the container, defined in values.yaml
          image: {{ .Values.image.repository }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.containerPort }}